/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type DisablePullRequestAutoMerge = {
    disablePullRequestAutoMerge: ({
        pullRequest: ({
            id: string;
        }) | null;
    }) | null;
};
export type DisablePullRequestAutoMergeVariables = {
    id: string;
};
