/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type GetPullRequest = {
    repository: ({
        pullRequest: ({
            body: string;
            title: string;
            number: number;
            headRefName: string;
            baseRefName: string;
        }) | null;
    }) | null;
};
export type GetPullRequestVariables = {
    owner: string;
    repo: string;
    number: number;
};
