/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type GetRelatedIssues = {
    repository: ({
        pullRequest: ({
            closingIssuesReferences: ({
                nodes: (({
                    id: string;
                    title: string;
                    number: number;
                }) | null)[] | null;
            }) | null;
        }) | null;
    }) | null;
};
export type GetRelatedIssuesVariables = {
    owner: string;
    repo: string;
    number: number;
};
