/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type GetPullRequest = {
    repository: ({
        pullRequest: ({
            body: string;
            title: string;
            number: number;
            headRefName: string;
            baseRefName: string;
            id: string;
            mergeable: "CONFLICTING" | "MERGEABLE" | "UNKNOWN";
            author: ({
                login: string;
            }) | null;
            commits: {
                totalCount: number;
                nodes: (({
                    commit: {
                        additions: number;
                        deletions: number;
                        message: string;
                        authoredByCommitter: boolean;
                        authors: {
                            nodes: (({
                                name: string | null;
                                email: string | null;
                                user: ({
                                    login: string;
                                }) | null;
                            }) | null)[] | null;
                        };
                    };
                }) | null)[] | null;
            };
            autoMergeRequest: ({
                commitBody: string | null;
                commitHeadline: string | null;
                enabledAt: any | null;
            }) | null;
        }) | null;
    }) | null;
};
export type GetPullRequestVariables = {
    owner: string;
    repo: string;
    number: number;
};
