name: 'Get next branch'
description: 'Gets the next branch name for forward merging. For example, if the current branch is "master", the next branch will be "prerelease/minor"'
author: 'Workday'
inputs:
  branch:
    description: 'The current branch name. If not provided, it will default to the current ref provided by the Github Action (whatever ref triggered the job)'
outputs:
  branch:
    description: 'The next branch name'
runs:
  using: 'node18'
  main: '../dist/actions/getNextBranch.js'
